version: '3.9'
services:
  postgres:
    container_name: ${APPLICATION_NAME}_postgres
    image: postgres:13
    restart: always
    hostname: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${APPLICATION_NAME}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - develop
  kit:
    container_name: ${APPLICATION_NAME}_${APPLICATION_NAME}
    restart: always
    image: ${APPLICATION_NAME}
    build:
      context: ./build/libs
    expose:
      - "8081"
    ports:
      - "8081:8081"
      - "10005:8000"
    networks:
      - develop
    depends_on:
      - postgres
networks:
  develop:
    driver: bridge
volumes:
  pgdata:
    name: ${POSTGRES_VOLUME_NAME}
