server:
  port: 8081

spring:
  application:
    name: kit
  datasource:
    url: jdbc:postgresql://localhost:54320/kit
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
  flyway:
    locations: classpath:/db/migration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
