server:
  port: 8081
  http2:
    enabled: true
  max-http-header-size: 48000

spring:
  application:
    name: kit
  datasource:
    url: jdbc:postgresql://postgres:5432/kit
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
  flyway:
    locations: classpath:/db/migration
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
