server:
  port: 8081
  http2:
    enabled: true
  max-http-header-size: 48000

spring:
  application:
    name: kit
  datasource:
    url: jdbc:postgresql://postgres:5432/kit
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    hikari:
      leak-detection-threshold: 30000
  flyway:
    out-of-order: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false

# if swagger-ui.enabled=true, it will be available at http://localhost:8081/swagger-ui/index.html?url=/v3/api-docs
# if not, then at https://petstore.swagger.io/?url=http://localhost:8081/v3/api-docs/
# schema is available at http://localhost:8081/v3/api-docs/
springdoc:
  swagger-ui:
    enabled: true

app:
  version: @gitTagVersion@
  git-hash: @gitHash@
